basic_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views


app_name = 'basic_app'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.index, name='index'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

learning_user/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),

]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',  blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate


def index(request):
    return render(request, 'basic_app/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))


@login_required
def special(request):
    return HttpResponse("Yes you are logged in")


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered' : registered,
    })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('basic_app:index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and fail")
            print(f"User name {username} Password {password}")
            return HttpResponse("Invalid Username Password")

    else:
        return render(request, 'basic_app/login.html', {} )

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
 <nav class="navbar navbar-default nevbar-static-top">
     <div class="container">
         <ul class="nav navbar nav">
             <li ><a class="navbar-brand" href="{% url 'basic_app:index' %}">Django</a></li>
             <li ><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
             <li ><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
            {% if user.is_authenticated %}
              <li ><a class="navbar-link" href="{% url 'basic_app:logout' %}">Logout</a></li>
                {% else %}
                <li ><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
             {% endif %}
         </ul>
      </div>
 </nav>
 <div class="container">
{% block body %}
{% endblock %}
 </div>

</body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body %}
    <div class="jumbotron">
    <h1>Django</h1>
    </div>
{% endblock%}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body %}
    <div class="jumbotron">
    <h1>Please Login</h1>
    <form method="post" action="{% url 'basic_app:user_login' %}">
        {% csrf_token %}
        <label for = "username">Username:</label>
        <input type="text" placeholder="Enter Username" name="username" >
        <label for = "password" >Password</label>
        <input type="password" placeholder="password" name="password">
        <input type="submit" value="">
    </form>
    </div>
{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body %}
    <div class="jumbotron">
        {% if registered %}
        <h1>Thanks for registering</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3> Fill out the form:</h3>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="register">
            {% endif %}

        </form>
    </div>

{% endblock %}